[package]
name = "wiggle-generator"
version = "0.1.0"
authors = ["ge9x"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
